In [18]:
import pandas as pd

df = pd.read_csv(r"../Data/Luxury_Housing_Bangalore.csv")
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [2]:
df.shape

(101000, 18)

In [4]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [14]:
df.dtypes

Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr          object
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [2]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [10]:
value=df.duplicated().sum()
print(value)

1000

In [15]:
df[df.duplicated(keep=False)]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [17]:
df[df.duplicated(subset=['Property_ID'], keep=False)]
df = [df['Property_ID']=='PROP000157']

In [11]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [13]:
df['Unit_Size_Sqft'].unique()

array([4025., 5760., 7707., ..., 3000., 3238., 5432.], shape=(6002,))

In [16]:
len(df)

101000

In [ ]:
(df.isnull().sum()/len(df))*100 
# Unit_Size_Sqft ,  Ticket_Price_Cr   , Amenity_Score   ,Buyer_Comments

Property_ID              0.000000
Micro_Market             0.000000
Project_Name             0.000000
Developer_Name           0.000000
Unit_Size_Sqft           9.946535
Configuration            0.000000
Ticket_Price_Cr          9.919802
Transaction_Type         0.000000
Buyer_Type               0.000000
Purchase_Quarter         0.000000
Connectivity_Score       0.000000
Amenity_Score            9.990099
Possession_Status        0.000000
Sales_Channel            0.000000
NRI_Buyer                0.000000
Locality_Infra_Score     0.000000
Avg_Traffic_Time_Min     0.000000
Buyer_Comments          18.105941
dtype: float64

In [22]:
df['Amenity_Score']

0         5.462863
1              NaN
2         8.669227
3         5.720246
4         8.609649
            ...
100995    6.221131
100996    9.783611
100997    8.383013
100998    5.756247
100999    9.989290
Name: Amenity_Score, Length: 101000, dtype: float64

In [23]:
df.isna()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [33]:
df['Unit_Size_Sqft'].value_counts()

Unit_Size_Sqft
-1.0       505
 4058.0     33
 6868.0     32
 7617.0     31
 5084.0     30
          ...
 5583.0      5
 6737.0      5
 7918.0      4
 4854.0      4
 6688.0      4
Name: count, Length: 6001, dtype: int64

In [26]:
df['Ticket_Price_Cr'].value_counts()

Ticket_Price_Cr
100.0                 278
70.0                  271
60.0                  268
₹100.0 Cr              73
₹70.0 Cr               64
                     ...
14.649171964451835      1
10.458397187932558      1
9.011186919073644       1
8.069051401340396       1
9.396367494232896       1
Name: count, Length: 72854, dtype: int64

In [27]:
df['Amenity_Score'].value_counts()

Amenity_Score
9.057120    2
9.892876    2
7.912356    2
9.284995    2
8.671261    2
           ..
5.909716    1
6.867291    1
9.907507    1
7.822984    1
7.552241    1
Name: count, Length: 90000, dtype: int64

# 31 March 2026

In [1]:
import pandas as pd

df = pd.read_csv(r"../Data/Luxury_Housing_Bangalore.csv")
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [3]:
df_copy = df.copy()

In [4]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

# Data Cleaning

In [5]:
df_copy['Ticket_Price_Cr']=df_copy['Ticket_Price_Cr'].str.replace('Cr','')
df_copy['Ticket_Price_Cr']=df_copy['Ticket_Price_Cr'].str.replace('₹','')
df_copy['Ticket_Price_Cr']=df_copy['Ticket_Price_Cr'].astype(float)

In [6]:
df_copy['Configuration']=df_copy['Configuration'].str.upper()

In [7]:
df_copy['Micro_Market'] = df_copy['Micro_Market'].str.strip().str.title()

In [8]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(5), int64(1), object(12)
memory usage: 13.9+ MB

In [9]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [10]:
df_value=df_copy['Unit_Size_Sqft'].isna()
df_copy[df_value]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
17,PROP000018,Yelahanka,Project_17,L&T Realty,NaN,4BHK,9.045290,Secondary,CXO,2024-03-31,8.793448,5.186328,Ready to move,NRI Desk,yes,9.256085,77,Loved the amenities!
18,PROP000019,Yelahanka,Project_18,Total Environment,NaN,5BHK+,7.623657,Primary,Other,2024-12-31,6.111031,6.898634,Ready to move,Broker,yes,8.652232,118,Connectivity is poor.
24,PROP000025,Mg Road,Project_24,L&T Realty,NaN,3BHK,13.640000,Primary,Other,2024-03-31,9.300782,9.464122,Under construction,Online,no,8.127972,43,Agent was not responsive.
33,PROP000034,Jp Nagar,Project_33,Tata Housing,NaN,5BHK+,15.018780,Primary,CXO,2024-09-30,7.991544,5.489478,Ready to move,Direct,yes,6.337526,64,Great value for money.
45,PROP000046,Mg Road,Project_45,Brigade,NaN,5BHK+,15.671783,Primary,NRI,2023-12-31,8.186105,9.515085,Launch,NRI Desk,yes,5.414198,57,Agent was not responsive.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100946,PROP068368,Rajajinagar,Project_367,Sobha,NaN,5BHK+,10.025178,Secondary,NRI,2023-12-31,8.567535,5.013950,Under construction,NRI Desk,yes,6.705184,15,Loved the amenities!
100953,PROP068005,Mg Road,Project_4,Total Environment,NaN,3BHK,6.719055,Secondary,Startup Founder,2023-12-31,9.345955,8.484690,Under construction,Broker,no,9.250374,104,Loved the amenities!
100958,PROP057589,Bellary Road,Project_88,RMZ,NaN,5BHK+,10.426678,Primary,NRI,2024-12-31,8.000070,8.857594,Under construction,NRI Desk,yes,9.588207,95,Too far from my office.
100966,PROP084077,Jayanagar,Project_76,Prestige,NaN,4BHK,14.490629,Primary,HNI,2023-06-30,7.193573,5.904934,Ready to move,Direct,no,5.996074,113,Great value for money.
100992,PROP064846,Kanakapura Road,Project_345,Prestige,NaN,3BHK,12.467955,Secondary,HNI,2023-12-31,6.047293,9.163434,Launch,Broker,no,7.544191,78,Excellent location!

In [11]:
df_copy[df_copy[['Unit_Size_Sqft','Ticket_Price_Cr','Amenity_Score']].isna().all(axis=1)]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
982,PROP000983,Mg Road,Project_482,SNN Raj,NaN,5BHK+,NaN,Primary,HNI,2024-12-31,6.017228,NaN,Launch,NRI Desk,no,6.046214,64,Connectivity is poor.
3524,PROP003525,Sarjapur Road,Project_24,L&T Realty,NaN,4BHK,NaN,Secondary,Startup Founder,2024-06-30,8.284245,NaN,Ready to move,Broker,yes,9.383054,19,NaN
3847,PROP003848,Mg Road,Project_347,Prestige,NaN,5BHK+,NaN,Secondary,HNI,2025-03-31,9.092382,NaN,Ready to move,NRI Desk,yes,5.655616,41,Agent was not responsive.
4708,PROP004709,Indiranagar,Project_208,Embassy,NaN,3BHK,NaN,Primary,Startup Founder,2023-12-31,8.001105,NaN,Under construction,Online,no,6.969850,50,Too far from my office.
7597,PROP007598,Bannerghatta Road,Project_97,Total Environment,NaN,5BHK+,NaN,Primary,NRI,2024-12-31,6.512736,NaN,Launch,Online,yes,8.066100,85,Great value for money.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98422,PROP098423,Electronic City,Project_422,L&T Realty,NaN,4BHK,NaN,Secondary,Other,2024-03-31,4.760940,NaN,Launch,Direct,no,9.673220,114,Too far from my office.
98839,PROP098840,Jp Nagar,Project_339,Brigade,NaN,5BHK+,NaN,Secondary,CXO,2024-09-30,8.397245,NaN,Under construction,Broker,yes,7.114010,77,Will buy after possession.
99567,PROP099568,Yelahanka,Project_67,Embassy,NaN,3BHK,NaN,Secondary,Startup Founder,2024-03-31,7.508621,NaN,Launch,Online,yes,7.369013,88,Loved the amenities!
99809,PROP099810,Sarjapur Road,Project_309,Sobha,NaN,4BHK,NaN,Primary,NRI,2025-03-31,8.741259,NaN,Under construction,Direct,no,8.852220,72,Will buy after possession.
100146,PROP004709,Indiranagar,Project_208,Embassy,NaN,3BHK,NaN,Primary,Startup Founder,2023-12-31,8.001105,NaN,Under construction,Online,no,6.969850,50,Too far from my office.

In [12]:
# drop columns with all null values in 'Unit_Size_Sqft' , 'Ticket_Price_Cr'  and 'Amenity_Score'
df_copy=df_copy.dropna(subset=['Unit_Size_Sqft','Ticket_Price_Cr','Amenity_Score'], how='all')

In [13]:
df_copy[df_copy[['Unit_Size_Sqft','Ticket_Price_Cr','Amenity_Score']].isna().all(axis=1)]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments]
Index: []

In [14]:
df_copy[df_copy[['Unit_Size_Sqft','Ticket_Price_Cr']].isna().all(axis=1)]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
129,PROP000130,Mg Road,Project_129,Total Environment,NaN,5BHK+,NaN,Primary,Other,2023-06-30,7.918198,7.892075,Launch,Online,no,5.417263,67,Underpriced for location.
152,PROP000153,Hebbal,Project_152,Puravankara,NaN,4BHK,NaN,Primary,CXO,2024-06-30,5.153752,8.889801,Launch,NRI Desk,no,9.960069,88,Will buy after possession.
267,PROP000268,Yelahanka,Project_267,Godrej,NaN,5BHK+,NaN,Primary,HNI,2024-09-30,5.909174,6.641576,Ready to move,NRI Desk,yes,5.680592,82,Will buy after possession.
333,PROP000334,Koramangala,Project_333,Embassy,NaN,5BHK+,NaN,Secondary,NRI,2025-03-31,6.070249,7.736236,Ready to move,Online,no,5.689435,40,Agent was not responsive.
392,PROP000393,Electronic City,Project_392,Sobha,NaN,5BHK+,NaN,Primary,Other,2024-09-30,9.721637,8.845899,Ready to move,Direct,no,8.165096,86,Great view from 15th floor.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100695,PROP094260,Jp Nagar,Project_259,Godrej,NaN,4BHK,NaN,Secondary,HNI,2023-06-30,6.212863,5.544353,Under construction,NRI Desk,yes,9.121717,88,Great value for money.
100713,PROP006076,Yelahanka,Project_75,Puravankara,NaN,4BHK,NaN,Primary,Startup Founder,2023-09-30,6.963042,9.853261,Ready to move,NRI Desk,no,5.622549,114,NaN
100895,PROP047325,Mg Road,Project_324,RMZ,NaN,3BHK,NaN,Secondary,Startup Founder,2024-12-31,6.007043,5.807065,Ready to move,Broker,yes,7.319403,110,Great value for money.
100916,PROP051868,Kanakapura Road,Project_367,Prestige,NaN,5BHK+,NaN,Secondary,HNI,2025-03-31,8.942969,7.174169,Under construction,Online,yes,6.628924,81,NaN
100943,PROP084598,Sarjapur Road,Project_97,Godrej,NaN,3BHK,NaN,Primary,HNI,2025-03-31,6.994397,9.565802,Under construction,Online,yes,8.249145,37,Connectivity is poor.

In [ ]:
# drop rows with all null values in 'Unit_Size_Sqft' , 'Ticket_Price_Cr' 
df_copy=df_copy.dropna(subset=['Unit_Size_Sqft','Ticket_Price_Cr'], how='all')

In [16]:
df_copy[df_copy[['Unit_Size_Sqft','Ticket_Price_Cr']].isna().all(axis=1)]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments]
Index: []

In [17]:
df_copy.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9097
Configuration               0
Ticket_Price_Cr          9070
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10008
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18110
dtype: int64

In [18]:
# Include mean/median values for 'Unit_Size_Sqft' and 'Ticket_Price_Cr' to fill the null values in the respective columns
df_copy=df_copy.fillna(
                        {   
                            'Unit_Size_Sqft':df_copy['Unit_Size_Sqft'].mean(),
                            'Ticket_Price_Cr':df_copy['Ticket_Price_Cr'].median(),
                            'Amenity_Score':df_copy['Amenity_Score'].median()
                        }
                      )

In [19]:
df_copy.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18110
dtype: int64

In [20]:
df_copy['Buyer_Comments'].unique()

array(['Loved the amenities!', nan, 'Agent was not responsive.',
       'Excellent location!', 'Too far from my office.',
       'Underpriced for location.', 'Will buy after possession.',
       'Great value for money.', 'Connectivity is poor.',
       'Great view from 15th floor.'], dtype=object)

In [21]:
# Fill the null values in 'Buyer_Comments' column with the previous non-null value using forward fill method
df_copy=df_copy.fillna({'Buyer_Comments': df_copy['Buyer_Comments'].ffill()})

In [22]:
df_copy['Buyer_Comments'].unique()

array(['Loved the amenities!', 'Agent was not responsive.',
       'Excellent location!', 'Too far from my office.',
       'Underpriced for location.', 'Will buy after possession.',
       'Great value for money.', 'Connectivity is poor.',
       'Great view from 15th floor.'], dtype=object)

In [23]:
df_copy.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

In [24]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499079,Under construction,NRI Desk,no,7.723898,106,Loved the amenities!
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [25]:
df_copy[df_copy.duplicated(keep=False)]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,Bellary Road,Project_50,Total Environment,7385.0,4BHK,8.740335,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,Rajajinagar,Project_150,L&T Realty,8678.0,5BHK+,9.321531,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3BHK,12.470000,Secondary,HNI,2023-09-30,4.279519,7.499079,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,Jayanagar,Project_324,Sobha,4648.0,3BHK,12.037647,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
485,PROP000486,Jayanagar,Project_485,L&T Realty,5258.0,4BHK,9.838688,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [134]:
df_copy[df_copy.duplicated()]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,Domlur,Project_223,Embassy,4608.000000,5BHK+,6.567529,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,Great view from 15th floor.
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.000000,5BHK+,12.037647,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,Rajajinagar,Project_495,Prestige,3778.000000,4BHK,12.568327,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,Domlur,Project_119,Brigade,5972.274765,4BHK,12.590000,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,Whitefield,Project_228,Total Environment,7458.000000,4BHK,13.713149,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.000000,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.000000,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.000000,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.000000,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.000000,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [26]:
# delete the duplicate rows and keep the first occurrence
df_copy=df_copy.drop_duplicates(keep='first')

In [27]:
df_copy[df_copy.duplicated()]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments]
Index: []

In [28]:
df_copy[df_copy.duplicated(keep=False)]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments]
Index: []

In [29]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499079,Under construction,NRI Desk,no,7.723898,106,Loved the amenities!
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100945,PROP061948,Jp Nagar,Project_447,Brigade,5042.0,4BHK,10.890000,Primary,HNI,2023-06-30,4.477990,5.388602,Ready to move,Broker,no,9.189129,110,Excellent location!
100954,PROP047570,Bannerghatta Road,Project_69,Puravankara,7768.0,4BHK,13.818040,Secondary,Other,2025-03-31,5.234031,7.499079,Ready to move,Direct,no,8.670540,91,Loved the amenities!
100957,PROP059496,Jayanagar,Project_495,L&T Realty,6394.0,3BHK,10.211912,Secondary,Startup Founder,2024-03-31,4.584414,5.720975,Launch,Broker,no,6.713494,106,Loved the amenities!
100969,PROP042059,Electronic City,Project_58,Embassy,4283.0,4BHK,12.037647,Secondary,HNI,2024-12-31,9.760059,7.056952,Under construction,NRI Desk,yes,9.391943,31,Loved the amenities!
100984,PROP033752,Mg Road,Project_251,RMZ,7215.0,4BHK,9.350494,Secondary,NRI,2024-03-31,4.388049,8.778185,Launch,NRI Desk,no,5.214259,70,Connectivity is poor.

In [ ]:
# Calculate the price per squarefeet and create a new column 'Price_per_Sqft'
df_copy['Price_per_Sqft'] = ((df_copy['Ticket_Price_Cr']*10000000)/df_copy['Unit_Size_Sqft']).round(2)

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\73136298.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Price_per_Sqft'] = ((df_copy['Ticket_Price_Cr']*10000000)/df_copy['Unit_Size_Sqft']   ).round(2)

In [31]:
df_copy['Purchase_Quarter']=pd.to_datetime(df_copy['Purchase_Quarter'])

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\2985299528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Purchase_Quarter']=pd.to_datetime(df_copy['Purchase_Quarter'])

In [32]:
# Extract the quarter number from the 'Purchase_Quarter' column and create a new column 'Quarter_Number'
df_copy['Quarter_Number']=df_copy['Purchase_Quarter'].dt.quarter

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\2500768160.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Quarter_Number']=df_copy['Purchase_Quarter'].dt.quarter

In [33]:
df_copy[['Purchase_Quarter', 'Quarter_Number']]

       Purchase_Quarter  Quarter_Number
0            2025-03-31               1
1            2024-06-30               2
2            2023-12-31               4
3            2024-03-31               1
4            2024-12-31               4
...                 ...             ...
100945       2023-06-30               2
100954       2025-03-31               1
100957       2024-03-31               1
100969       2024-12-31               4
100984       2024-03-31               1

[99228 rows x 2 columns]

In [34]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99228 entries, 0 to 100984
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           99228 non-null  object
 1   Micro_Market          99228 non-null  object
 2   Project_Name          99228 non-null  object
 3   Developer_Name        99228 non-null  object
 4   Unit_Size_Sqft        99228 non-null  float64
 5   Configuration         99228 non-null  object
 6   Ticket_Price_Cr       99228 non-null  float64
 7   Transaction_Type      99228 non-null  object
 8   Buyer_Type            99228 non-null  object
 9   Purchase_Quarter      99228 non-null  datetime64[ns]
 10  Connectivity_Score    99228 non-null  float64
 11  Amenity_Score         99228 non-null  float64
 12  Possession_Status     99228 non-null  object
 13  Sales_Channel         99228 non-null  object
 14  NRI_Buyer             99228 non-null  object
 15  Locality_Infra_Score  99228 non-null  float64
 16  Avg_Traffic_Time_Min  99228 non-null  int64
 17  Buyer_Comments        99228 non-null  object
 18  Price_per_Sqft        99228 non-null  float64
 19  Quarter_Number        99228 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(11)
memory usage: 15.5+ MB

In [35]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31679.12,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499079,Under construction,NRI Desk,no,7.723898,106,Loved the amenities!,28284.99,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13646.98,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15175.01,1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21471.10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100945,PROP061948,Jp Nagar,Project_447,Brigade,5042.0,4BHK,10.890000,Primary,HNI,2023-06-30,4.477990,5.388602,Ready to move,Broker,no,9.189129,110,Excellent location!,21598.57,2
100954,PROP047570,Bannerghatta Road,Project_69,Puravankara,7768.0,4BHK,13.818040,Secondary,Other,2025-03-31,5.234031,7.499079,Ready to move,Direct,no,8.670540,91,Loved the amenities!,17788.41,1
100957,PROP059496,Jayanagar,Project_495,L&T Realty,6394.0,3BHK,10.211912,Secondary,Startup Founder,2024-03-31,4.584414,5.720975,Launch,Broker,no,6.713494,106,Loved the amenities!,15971.09,1
100969,PROP042059,Electronic City,Project_58,Embassy,4283.0,4BHK,12.037647,Secondary,HNI,2024-12-31,9.760059,7.056952,Under construction,NRI Desk,yes,9.391943,31,Loved the amenities!,28105.64,4
100984,PROP033752,Mg Road,Project_251,RMZ,7215.0,4BHK,9.350494,Secondary,NRI,2024-03-31,4.388049,8.778185,Launch,NRI Desk,no,5.214259,70,Connectivity is poor.,12959.80,1

In [36]:
df_copy['Possession_Status'].unique()

array(['Launch', 'Under construction', 'Ready to move'], dtype=object)

In [37]:
df_copy['Transaction_Type'].unique()

array(['Primary', 'Secondary'], dtype=object)

In [38]:
df_copy['Booking_Flag']=df_copy['Possession_Status'].apply(lambda x: 1 if x=='Ready to move' else 0)

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\4128526710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Booking_Flag']=df_copy['Possession_Status'].apply(lambda x: 1 if x=='Ready to move' else 0)

In [40]:
df_copy['Booking_Flag']=df_copy['Transaction_Type'].apply(lambda x: 1 if x=='Primary' else 0)

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\2402287479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Booking_Flag']=df_copy['Transaction_Type'].apply(lambda x: 1 if x=='Primary' else 0)

In [41]:
df_copy[['Transaction_Type','Booking_Flag']]

       Transaction_Type  Booking_Flag
0               Primary             1
1               Primary             1
2               Primary             1
3               Primary             1
4             Secondary             0
...                 ...           ...
100945          Primary             1
100954        Secondary             0
100957        Secondary             0
100969        Secondary             0
100984        Secondary             0

[99228 rows x 2 columns]

In [42]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99228 entries, 0 to 100984
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           99228 non-null  object
 1   Micro_Market          99228 non-null  object
 2   Project_Name          99228 non-null  object
 3   Developer_Name        99228 non-null  object
 4   Unit_Size_Sqft        99228 non-null  float64
 5   Configuration         99228 non-null  object
 6   Ticket_Price_Cr       99228 non-null  float64
 7   Transaction_Type      99228 non-null  object
 8   Buyer_Type            99228 non-null  object
 9   Purchase_Quarter      99228 non-null  datetime64[ns]
 10  Connectivity_Score    99228 non-null  float64
 11  Amenity_Score         99228 non-null  float64
 12  Possession_Status     99228 non-null  object
 13  Sales_Channel         99228 non-null  object
 14  NRI_Buyer             99228 non-null  object
 15  Locality_Infra_Score  99228 non-null  float64
 16  Avg_Traffic_Time_Min  99228 non-null  int64
 17  Buyer_Comments        99228 non-null  object
 18  Price_per_Sqft        99228 non-null  float64
 19  Quarter_Number        99228 non-null  int32
 20  Booking_Flag          99228 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(2), object(11)
memory usage: 16.3+ MB

In [45]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31679.12,1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,7.499079,Under construction,NRI Desk,no,7.723898,106,Loved the amenities!,28284.99,2,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13646.98,4,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15175.01,1,1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21471.10,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100945,PROP061948,Jp Nagar,Project_447,Brigade,5042.0,4BHK,10.890000,Primary,HNI,2023-06-30,...,5.388602,Ready to move,Broker,no,9.189129,110,Excellent location!,21598.57,2,1
100954,PROP047570,Bannerghatta Road,Project_69,Puravankara,7768.0,4BHK,13.818040,Secondary,Other,2025-03-31,...,7.499079,Ready to move,Direct,no,8.670540,91,Loved the amenities!,17788.41,1,0
100957,PROP059496,Jayanagar,Project_495,L&T Realty,6394.0,3BHK,10.211912,Secondary,Startup Founder,2024-03-31,...,5.720975,Launch,Broker,no,6.713494,106,Loved the amenities!,15971.09,1,0
100969,PROP042059,Electronic City,Project_58,Embassy,4283.0,4BHK,12.037647,Secondary,HNI,2024-12-31,...,7.056952,Under construction,NRI Desk,yes,9.391943,31,Loved the amenities!,28105.64,4,0
100984,PROP033752,Mg Road,Project_251,RMZ,7215.0,4BHK,9.350494,Secondary,NRI,2024-03-31,...,8.778185,Launch,NRI Desk,no,5.214259,70,Connectivity is poor.,12959.80,1,0

In [46]:
df_copy['NRI_Buyer'].unique()

array(['yes', 'no'], dtype=object)

In [47]:
df_copy['NRI_Buyer'] = df_copy['NRI_Buyer'].str.strip().str.title()

C:\Users\nisha\AppData\Local\Temp\ipykernel_28576\1371105784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['NRI_Buyer'] = df_copy['NRI_Buyer'].str.strip().str.title()

In [48]:
df_copy

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.12,1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,7.499079,Under construction,NRI Desk,No,7.723898,106,Loved the amenities!,28284.99,2,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.98,4,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,Yes,6.100929,106,Excellent location!,15175.01,1,1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,No,5.312510,18,Too far from my office.,21471.10,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100945,PROP061948,Jp Nagar,Project_447,Brigade,5042.0,4BHK,10.890000,Primary,HNI,2023-06-30,...,5.388602,Ready to move,Broker,No,9.189129,110,Excellent location!,21598.57,2,1
100954,PROP047570,Bannerghatta Road,Project_69,Puravankara,7768.0,4BHK,13.818040,Secondary,Other,2025-03-31,...,7.499079,Ready to move,Direct,No,8.670540,91,Loved the amenities!,17788.41,1,0
100957,PROP059496,Jayanagar,Project_495,L&T Realty,6394.0,3BHK,10.211912,Secondary,Startup Founder,2024-03-31,...,5.720975,Launch,Broker,No,6.713494,106,Loved the amenities!,15971.09,1,0
100969,PROP042059,Electronic City,Project_58,Embassy,4283.0,4BHK,12.037647,Secondary,HNI,2024-12-31,...,7.056952,Under construction,NRI Desk,Yes,9.391943,31,Loved the amenities!,28105.64,4,0
100984,PROP033752,Mg Road,Project_251,RMZ,7215.0,4BHK,9.350494,Secondary,NRI,2024-03-31,...,8.778185,Launch,NRI Desk,No,5.214259,70,Connectivity is poor.,12959.80,1,0