# 06 April 2024

In [1]:
import pandas as pd

df = pd.read_csv(r"..\Data\youtube_ad_revenue_dataset.csv")
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [2]:
df_copy = df.copy()

In [3]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122400 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              122400 non-null  object
 1   date                  122400 non-null  object
 2   views                 122400 non-null  int64
 3   likes                 116283 non-null  float64
 4   comments              116288 non-null  float64
 5   watch_time_minutes    116295 non-null  float64
 6   video_length_minutes  122400 non-null  float64
 7   subscribers           122400 non-null  int64
 8   category              122400 non-null  object
 9   device                122400 non-null  object
 10  country               122400 non-null  object
 11  ad_revenue_usd        122400 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 11.2+ MB

In [4]:
df_copy.shape

(122400, 12)

In [5]:
df_copy.isnull().sum()

video_id                   0
date                       0
views                      0
likes                   6117
comments                6112
watch_time_minutes      6105
video_length_minutes       0
subscribers                0
category                   0
device                     0
country                    0
ad_revenue_usd             0
dtype: int64

In [6]:
df_copy.isna().sum()*100/len(df_copy)

video_id                0.000000
date                    0.000000
views                   0.000000
likes                   4.997549
comments                4.993464
watch_time_minutes      4.987745
video_length_minutes    0.000000
subscribers             0.000000
category                0.000000
device                  0.000000
country                 0.000000
ad_revenue_usd          0.000000
dtype: float64

In [15]:
df_copy[df_copy[['likes','comments','watch_time_minutes']].isna().all(axis=1)]

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
5469,vid_4475,2024-06-21 10:50:40.993199,10139,NaN,NaN,NaN,6.364777,227603,Gaming,Tablet,CA,333.275924
11507,vid_3668,2024-08-31 10:50:40.993199,9957,NaN,NaN,NaN,24.542532,397961,Entertainment,Mobile,UK,272.177411
16545,vid_2601,2025-03-31 10:50:40.993199,9952,NaN,NaN,NaN,3.813444,439235,Lifestyle,Desktop,AU,243.016959
35260,vid_4105,2025-01-07 10:50:40.993199,9978,NaN,NaN,NaN,28.826886,318253,Entertainment,TV,CA,143.513288
45723,vid_4036,2025-04-11 10:50:40.993199,9918,NaN,NaN,NaN,19.237855,975813,Tech,TV,IN,303.699582
53325,vid_2594,2024-12-12 10:50:40.993199,9987,NaN,NaN,NaN,16.960052,762503,Education,Mobile,DE,311.190360
55760,vid_3761,2025-01-05 10:50:40.993199,9874,NaN,NaN,NaN,10.104454,78705,Lifestyle,TV,AU,344.716235
58162,vid_2219,2025-06-01 10:50:40.993199,10080,NaN,NaN,NaN,11.607372,361730,Entertainment,TV,UK,259.186559
87233,vid_4083,2025-04-13 10:50:40.993199,10124,NaN,NaN,NaN,14.017403,601259,Music,Tablet,IN,171.337829
87248,vid_1953,2024-06-15 10:50:40.993199,9841,NaN,NaN,NaN,18.163041,644385,Tech,Mobile,US,179.577227
92566,vid_4135,2025-03-10 10:50:40.993199,10035,NaN,NaN,NaN,12.366692,622125,Education,Tablet,DE,211.063969
92575,vid_353,2025-02-23 10:50:40.993199,9861,NaN,NaN,NaN,24.439536,732841,Music,Tablet,US,185.112037
93428,vid_2839,2025-05-29 10:50:40.993199,10154,NaN,NaN,NaN,12.080495,287529,Education,TV,UK,303.795404
107266,vid_927,2024-06-25 10:50:40.993199,10073,NaN,NaN,NaN,12.789954,428791,Entertainment,Desktop,US,342.851845
113642,vid_3679,2024-08-03 10:50:40.993199,10088,NaN,NaN,NaN,4.994559,615614,Music,Mobile,IN,273.867455
114061,vid_670,2025-06-07 10:50:40.993199,9953,NaN,NaN,NaN,15.489121,303404,Music,Mobile,US,270.365346
114327,vid_4911,2024-07-13 10:50:40.993199,9930,NaN,NaN,NaN,16.060413,544031,Music,TV,AU,252.164797
119849,vid_1608,2025-04-08 10:50:40.993199,10075,NaN,NaN,NaN,25.879457,718379,Music,Mobile,DE,192.360899

In [16]:
df_copy=df_copy.dropna(subset=['likes','comments','watch_time_minutes'], how='all')

In [9]:
df_copy['watch_time_minutes'].isna().sum()

np.int64(6087)

In [17]:
df_copy=df_copy.fillna({'watch_time_minutes':df_copy['watch_time_minutes'].median()})

In [18]:
null_value_status = df_copy.isna().sum()*100/len(df_copy)
null_value_status

video_id                0.000000
date                    0.000000
views                   0.000000
likes                   4.983576
comments                4.979490
watch_time_minutes      0.000000
video_length_minutes    0.000000
subscribers             0.000000
category                0.000000
device                  0.000000
country                 0.000000
ad_revenue_usd          0.000000
dtype: float64

In [19]:
df_copy[df_copy[['likes','comments']].isna().all(axis=1)]

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
368,vid_3569,2024-12-07 10:50:40.993199,10143,NaN,NaN,46261.643838,12.792502,784866,Entertainment,Desktop,IN,306.116510
545,vid_2410,2025-04-25 10:50:40.993199,9989,NaN,NaN,27866.106910,18.237211,45234,Tech,Desktop,IN,218.140823
1029,vid_399,2024-09-20 10:50:40.993199,9919,NaN,NaN,31672.667706,17.111673,659310,Entertainment,Mobile,DE,216.008369
1738,vid_974,2025-03-14 10:50:40.993199,10098,NaN,NaN,52300.654159,10.777081,986152,Education,Mobile,UK,328.973530
1875,vid_2046,2024-07-05 10:50:40.993199,9857,NaN,NaN,39917.054696,6.078603,6378,Music,Desktop,AU,260.363106
...,...,...,...,...,...,...,...,...,...,...,...,...
120597,vid_3576,2024-10-02 10:50:40.993199,9983,NaN,NaN,15867.536964,9.965505,447854,Education,Desktop,US,138.356136
120720,vid_2224,2024-07-21 10:50:40.993199,10204,NaN,NaN,24516.117429,6.900675,468237,Gaming,Mobile,AU,193.051877
120860,vid_4201,2024-11-26 10:50:40.993199,9946,NaN,NaN,37402.474189,5.571601,505937,Entertainment,Tablet,DE,258.390421
121037,vid_3712,2025-01-04 10:50:40.993199,10057,NaN,NaN,43824.564131,25.353009,242895,Entertainment,TV,CA,298.338056
121981,vid_1298,2025-05-07 10:50:40.993199,10142,NaN,NaN,38335.462057,3.907699,218151,Gaming,TV,DE,263.586827

In [20]:
df_copy=df_copy.dropna(subset=['likes','comments'], how='all')

In [21]:
null_value_status = df_copy.isna().sum()*100/len(df_copy)
null_value_status

video_id                0.000000
date                    0.000000
views                   0.000000
likes                   4.757107
comments                4.753012
watch_time_minutes      0.000000
video_length_minutes    0.000000
subscribers             0.000000
category                0.000000
device                  0.000000
country                 0.000000
ad_revenue_usd          0.000000
dtype: float64

In [22]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122091 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              122091 non-null  object
 1   date                  122091 non-null  object
 2   views                 122091 non-null  int64
 3   likes                 116283 non-null  float64
 4   comments              116288 non-null  float64
 5   watch_time_minutes    122091 non-null  float64
 6   video_length_minutes  122091 non-null  float64
 7   subscribers           122091 non-null  int64
 8   category              122091 non-null  object
 9   device                122091 non-null  object
 10  country               122091 non-null  object
 11  ad_revenue_usd        122091 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 12.1+ MB

In [6]:
df_copy.duplicated().sum()

np.int64(2400)

In [23]:
df_copy

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [24]:
df_copy['date']=pd.to_datetime(df_copy['date']).dt.floor('s')

In [25]:
df_copy['likes'] = df_copy['likes'].fillna(0)
df_copy['likes'] = df_copy['likes'].astype(int)
df_copy['comments'] = df_copy['comments'].fillna(0)
df_copy['comments'] = df_copy['comments'].astype(int)

In [26]:
null_value_status = df_copy.isna().sum()*100/len(df_copy)
null_value_status

video_id                0.0
date                    0.0
views                   0.0
likes                   0.0
comments                0.0
watch_time_minutes      0.0
video_length_minutes    0.0
subscribers             0.0
category                0.0
device                  0.0
country                 0.0
ad_revenue_usd          0.0
dtype: float64

In [27]:
df_copy.duplicated().sum()

np.int64(2395)

In [ ]:
df_copy[df_copy.duplicated()]

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
3179,vid_4608,2025-01-11 10:50:40.993199,9945,1458.0,121.0,31645.774111,15.206639,224801,Tech,Desktop,CA,228.151319
3231,vid_3134,2025-06-05 10:50:40.993199,10077,701.0,202.0,40120.596261,12.656050,580825,Tech,TV,UK,257.175292
3666,vid_25,2024-09-18 10:50:40.993199,9947,1802.0,347.0,55506.461433,5.456635,385325,Tech,Tablet,DE,350.450592
4710,vid_4926,2024-10-24 10:50:40.993199,9995,1286.0,292.0,34484.070853,4.757113,606881,Education,TV,DE,241.775903
4818,vid_4966,2025-02-10 10:50:40.993199,10034,776.0,447.0,34912.309423,2.488627,46916,Entertainment,Mobile,DE,237.896544
...,...,...,...,...,...,...,...,...,...,...,...,...
122163,vid_4644,2024-08-25 10:50:40.993199,10047,1948.0,307.0,16349.810313,10.084170,176249,Gaming,Mobile,IN,168.188062
122237,vid_2558,2024-07-27 10:50:40.993199,10028,1273.0,149.0,46832.765101,19.829163,733749,Tech,Tablet,DE,297.484978
122263,vid_4264,2024-09-30 10:50:40.993199,10035,563.0,457.0,NaN,10.365727,892745,Gaming,TV,AU,162.047770
122269,vid_2012,2025-06-07 10:50:40.993199,9919,688.0,152.0,58706.831545,18.868730,816381,Lifestyle,Mobile,IN,342.894716
122337,vid_1985,2025-05-17 10:50:40.993199,9924,NaN,373.0,37828.208105,12.282658,173977,Music,TV,UK,254.112670

In [35]:
df_copy[df_copy.duplicated(keep=False)].sort_values(by=['video_id','date'])

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
27583,vid_10,2024-11-25 10:50:40,10001,1877,316,45099.652444,26.862350,653429,Lifestyle,TV,DE,302.424925
101218,vid_10,2024-11-25 10:50:40,10001,1877,316,45099.652444,26.862350,653429,Lifestyle,TV,DE,302.424925
62274,vid_1003,2024-08-24 10:50:40,10038,1983,0,20195.328013,15.438654,648274,Lifestyle,TV,IN,189.141287
121655,vid_1003,2024-08-24 10:50:40,10038,1983,0,20195.328013,15.438654,648274,Lifestyle,TV,IN,189.141287
69681,vid_1003,2025-01-18 10:50:40,10010,1502,182,41836.974016,20.930565,850239,Lifestyle,Mobile,DE,278.341442
...,...,...,...,...,...,...,...,...,...,...,...,...
98228,vid_996,2024-10-31 10:50:40,9753,242,476,41331.898554,19.667345,680781,Music,Tablet,IN,258.018193
51660,vid_997,2025-04-25 10:50:40,9993,1970,185,22818.396793,24.373115,893529,Music,TV,AU,196.684348
86871,vid_997,2025-04-25 10:50:40,9993,1970,185,22818.396793,24.373115,893529,Music,TV,AU,196.684348
48302,vid_999,2024-09-15 10:50:40,9860,1541,472,35614.864714,26.618876,962885,Lifestyle,Tablet,CA,253.880166
60773,vid_999,2024-09-15 10:50:40,9860,1541,472,35614.864714,26.618876,962885,Lifestyle,Tablet,CA,253.880166

In [36]:
# delete the duplicate rows and keep the first occurrence
df_copy=df_copy.drop_duplicates(keep='first')

In [37]:
df_copy[df_copy.duplicated(keep=False)].sort_values(by=['video_id','date'])

Empty DataFrame
Columns: [video_id, date, views, likes, comments, watch_time_minutes, video_length_minutes, subscribers, category, device, country, ad_revenue_usd]
Index: []

In [38]:
df_copy[df_copy['likes'].isnull()==True]

Empty DataFrame
Columns: [video_id, date, views, likes, comments, watch_time_minutes, video_length_minutes, subscribers, category, device, country, ad_revenue_usd]
Index: []

In [39]:
df_copy[df_copy['video_id']=='vid_4434']

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
9,vid_4434,2025-04-16 10:50:40,10051,0,61,40011.579945,24.454723,103872,Tech,Tablet,DE,246.711883
831,vid_4434,2024-10-21 10:50:40,10032,552,380,20582.762887,15.173068,76474,Lifestyle,Desktop,DE,165.327445
3402,vid_4434,2025-03-31 10:50:40,9958,1870,49,53209.193740,20.020837,534179,Tech,Desktop,CA,335.724265
6617,vid_4434,2025-02-23 10:50:40,10025,0,268,32188.171504,6.010736,54859,Tech,Desktop,IN,226.484717
6679,vid_4434,2024-08-09 10:50:40,10226,1885,279,35147.010661,4.906668,887054,Tech,TV,AU,256.176745
8756,vid_4434,2025-01-08 10:50:40,9973,1146,130,25569.167063,29.361108,357397,Gaming,Mobile,UK,194.441062
11413,vid_4434,2024-06-14 10:50:40,9934,1756,303,18753.557988,10.739642,872232,Music,Desktop,UK,175.563121
21623,vid_4434,2024-11-03 10:50:40,9710,679,101,40075.613723,6.292049,851197,Education,Mobile,DE,252.936962
23455,vid_4434,2024-12-06 10:50:40,9845,1588,346,21777.002772,7.797197,841340,Tech,TV,DE,187.205115
26819,vid_4434,2025-05-23 10:50:40,9966,1785,194,20031.198453,11.639452,621026,Music,Desktop,US,180.378347
33920,vid_4434,2025-04-12 10:50:40,9938,843,276,15738.968428,20.879809,45797,Lifestyle,TV,CA,145.215461
39666,vid_4434,2025-02-13 10:50:40,9896,1677,397,38142.885217,15.832109,249877,Entertainment,Tablet,AU,267.034611
42648,vid_4434,2025-03-23 10:50:40,10024,1038,153,58923.576622,26.579705,182867,Education,TV,US,350.496421
48117,vid_4434,2024-10-17 10:50:40,10001,1799,439,20246.203083,5.351159,481016,Lifestyle,Tablet,DE,186.025882
50326,vid_4434,2024-07-09 10:50:40,9880,494,75,56343.135068,23.428543,725762,Lifestyle,Mobile,UK,326.890007
57719,vid_4434,2024-10-05 10:50:40,9946,1124,496,19313.051604,25.979997,234124,Education,Desktop,CA,170.718151
61779,vid_4434,2024-12-23 10:50:40,10061,389,465,46376.219599,14.360014,11746,Music,Mobile,CA,285.742105
62714,vid_4434,2024-11-25 10:50:40,9899,1231,415,52156.086603,26.028970,343496,Entertainment,Desktop,DE,325.759794
62760,vid_4434,2025-03-31 10:50:40,9937,966,272,37531.990337,5.951627,153031,Education,Tablet,US,183.186517
84251,vid_4434,2024-09-23 10:50:40,10054,617,64,57826.387927,17.916622,13012,Gaming,TV,CA,336.714448
85009,vid_4434,2025-01-05 10:50:40,10006,477,451,37531.990337,21.196343,531877,Tech,TV,AU,147.439582
86721,vid_4434,2025-05-10 10:50:40,10088,1042,254,37531.990337,22.447632,92844,Gaming,TV,US,149.347290
89702,vid_4434,2025-04-21 10:50:40,9926,1718,439,35860.608941,19.535960,985434,Education,TV,DE,257.857600
91772,vid_4434,2025-04-11 10:50:40,10006,1761,416,42869.779952,19.170996,750343,Music,Desktop,CA,291.663166
102654,vid_4434,2025-01-29 10:50:40,9734,294,311,23002.540513,20.963496,671538,Education,TV,US,169.562612
104668,vid_4434,2025-05-28 10:50:40,9724,1284,92,44396.813734,7.233239,855439,Lifestyle,Tablet,US,283.626021
109276,vid_4434,2025-01-04 10:50:40,9933,757,65,23525.416475,28.004634,630692,Lifestyle,Desktop,UK,176.794253
121026,vid_4434,2024-12-21 10:50:40,10074,1852,121,56192.684980,25.377710,92022,Education,Mobile,DE,351.322564

In [40]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119696 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              119696 non-null  object
 1   date                  119696 non-null  datetime64[ns]
 2   views                 119696 non-null  int64
 3   likes                 119696 non-null  int64
 4   comments              119696 non-null  int64
 5   watch_time_minutes    119696 non-null  float64
 6   video_length_minutes  119696 non-null  float64
 7   subscribers           119696 non-null  int64
 8   category              119696 non-null  object
 9   device                119696 non-null  object
 10  country               119696 non-null  object
 11  ad_revenue_usd        119696 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 11.9+ MB

In [41]:
df_copy.describe()

,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd
count,119696,119696.000000,119696.000000,119696.000000,119696.000000,119696.000000,119696.000000,119696.000000
mean,2024-12-08 03:32:06.459030016,9999.817730,1047.258847,261.294296,37540.553649,16.018134,502254.472998,252.709665
min,2024-06-09 10:50:40,9521.000000,0.000000,0.000000,14659.105562,2.000142,1005.000000,126.590603
25%,2024-09-07 10:50:40,9933.000000,581.000000,146.000000,26951.274051,9.003176,252516.000000,199.895130
50%,2024-12-08 10:50:40,10000.000000,1056.000000,263.000000,37531.990337,16.009460,503594.500000,252.677983
75%,2025-03-09 10:50:40,10067.000000,1525.000000,381.000000,48210.390223,23.027063,752334.000000,305.613497
max,2025-06-08 10:50:40,10468.000000,2061.000000,515.000000,61557.670089,29.999799,999997.000000,382.768254
std,NaN,99.926834,558.447201,139.443531,12658.962135,8.086050,288380.386641,61.954410

In [42]:
df_copy['watch_time_hours'] = df_copy['watch_time_minutes']/60

C:\Users\nisha\AppData\Local\Temp\ipykernel_25828\1509193164.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['watch_time_hours'] = df_copy['watch_time_minutes']/60

In [43]:
df_copy

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,watch_time_hours
0,vid_3092,2024-09-24 10:50:40,9936,1221,320,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,441.620236
1,vid_3459,2024-09-22 10:50:40,10017,642,346,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,253.495791
2,vid_4784,2024-11-21 10:50:40,10097,1979,187,57332.658498,26.200634,240534,Education,TV,CA,360.134008,955.544308
3,vid_4078,2025-01-28 10:50:40,10034,1191,242,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,522.241963
4,vid_3522,2025-04-28 10:50:40,9889,1858,477,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,261.094441
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40,9853,1673,147,42075.704885,25.490195,210818,Education,Tablet,US,280.986396,701.261748
122396,vid_3890,2024-07-13 10:50:40,10128,1709,63,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981,959.395051
122397,vid_3934,2024-06-10 10:50:40,10267,700,0,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106,459.161911
122398,vid_4260,2024-12-22 10:50:40,10240,1616,106,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811,949.456406
122399,vid_1056,2024-06-25 10:50:40,9931,770,0,38466.837135,27.305703,517587,Tech,TV,CA,253.842824,641.113952

In [44]:
df_copy['category'].unique()

array(['Entertainment', 'Gaming', 'Education', 'Music', 'Tech',
       'Lifestyle'], dtype=object)

In [45]:
# Frequency encoding
frequency_encoding = df_copy['category'].value_counts()
frequency_encoding

category
Education        20073
Music            20005
Tech             19982
Entertainment    19974
Gaming           19921
Lifestyle        19741
Name: count, dtype: int64

In [46]:
# Frequency encoding
frequency_encoding = df_copy['category'].value_counts()
df_copy['category_encoded'] = df_copy['category'].map(frequency_encoding)

C:\Users\nisha\AppData\Local\Temp\ipykernel_25828\1923570252.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['category_encoded'] = df_copy['category'].map(frequency_encoding)

In [47]:
df_copy['category_encoded'].unique()

array([19974, 19921, 20073, 20005, 19982, 19741])

In [48]:
#Which content type is most common on the platform?
df_copy.groupby('category_encoded')['watch_time_hours'].mean()

category_encoded
19741    623.214573
19921    628.057326
19974    624.727168
19982    628.313332
20005    624.700688
20073    625.023575
Name: watch_time_hours, dtype: float64

In [49]:
df_copy['device'].unique()

array(['TV', 'Tablet', 'Mobile', 'Desktop'], dtype=object)

In [50]:
df_copy['country'].unique()

array(['IN', 'CA', 'UK', 'US', 'DE', 'AU'], dtype=object)

In [51]:
from sklearn.preprocessing import LabelEncoder
encoder =LabelEncoder()
df_copy['device_encoded']=encoder.fit_transform(df_copy['device'])
df_copy['country_encoded']=encoder.fit_transform(df_copy['country'])

C:\Users\nisha\AppData\Local\Temp\ipykernel_25828\4019490764.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['device_encoded']=encoder.fit_transform(df_copy['device'])
C:\Users\nisha\AppData\Local\Temp\ipykernel_25828\4019490764.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['country_encoded']=encoder.fit_transform(df_copy['country'])

In [54]:
df_copy.isnull().sum()

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
watch_time_hours        0
category_encoded        0
device_encoded          0
country_encoded         0
dtype: int64

In [55]:
df_copy.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,watch_time_hours,category_encoded,device_encoded,country_encoded
0,vid_3092,2024-09-24 10:50:40,9936,1221,320,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,441.620236,19974,2,3
1,vid_3459,2024-09-22 10:50:40,10017,642,346,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,253.495791,19921,3,1
2,vid_4784,2024-11-21 10:50:40,10097,1979,187,57332.658498,26.200634,240534,Education,TV,CA,360.134008,955.544308,20073,2,1
3,vid_4078,2025-01-28 10:50:40,10034,1191,242,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,522.241963,19974,1,4
4,vid_3522,2025-04-28 10:50:40,9889,1858,477,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,261.094441,20073,1,1

In [60]:
df_copy['engagement_rate'] = (df_copy['likes'] + df_copy['comments']) / df_copy['views']

C:\Users\nisha\AppData\Local\Temp\ipykernel_25828\1199988168.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['engagement_rate'] = (df_copy['likes'] + df_copy['comments']) / df_copy['views']

In [61]:
df_copy.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,watch_time_hours,category_encoded,device_encoded,country_encoded,engagement_rate
0,vid_3092,2024-09-24 10:50:40,9936,1221,320,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,441.620236,19974,2,3,0.155093
1,vid_3459,2024-09-22 10:50:40,10017,642,346,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,253.495791,19921,3,1,0.098632
2,vid_4784,2024-11-21 10:50:40,10097,1979,187,57332.658498,26.200634,240534,Education,TV,CA,360.134008,955.544308,20073,2,1,0.214519
3,vid_4078,2025-01-28 10:50:40,10034,1191,242,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,522.241963,19974,1,4,0.142814
4,vid_3522,2025-04-28 10:50:40,9889,1858,477,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,261.094441,20073,1,1,0.236121

In [63]:
df_copy.isnull().sum()

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
watch_time_hours        0
category_encoded        0
device_encoded          0
country_encoded         0
engagement_rate         0
dtype: int64

In [64]:
df.shape

(122400, 12)

In [65]:
df_copy.shape

(119696, 17)

In [66]:
df_copy.to_csv(r"../Data/Cleaned_youtube_ad_revenue_dataset.csv", index=False)

# 17 April 2026

In [37]:
import pandas as pd

df = pd.read_csv(r"..\Data\youtube_ad_revenue_dataset.csv")
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [38]:
df_copy = df.copy()

In [39]:
df_copy

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [11]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122400 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              122400 non-null  object
 1   date                  122400 non-null  object
 2   views                 122400 non-null  int64
 3   likes                 116283 non-null  float64
 4   comments              116288 non-null  float64
 5   watch_time_minutes    116295 non-null  float64
 6   video_length_minutes  122400 non-null  float64
 7   subscribers           122400 non-null  int64
 8   category              122400 non-null  object
 9   device                122400 non-null  object
 10  country               122400 non-null  object
 11  ad_revenue_usd        122400 non-null  float64
dtypes: float64(5), int64(2), object(5)
memory usage: 11.2+ MB

In [40]:
df_copy.isnull().sum()

video_id                   0
date                       0
views                      0
likes                   6117
comments                6112
watch_time_minutes      6105
video_length_minutes       0
subscribers                0
category                   0
device                     0
country                    0
ad_revenue_usd             0
dtype: int64

In [41]:
df_copy=df_copy.dropna(subset=['likes','comments','watch_time_minutes'], how='all') 
df_copy=df_copy.dropna(subset=['likes','comments'], how='all') 
df_copy=df_copy.fillna({'watch_time_minutes':df_copy['watch_time_minutes'].median()})
df_copy['likes'] = df_copy['likes'].fillna(0)
df_copy['likes'] = df_copy['likes'].astype(int)
df_copy['comments'] = df_copy['comments'].fillna(0)
df_copy['comments'] = df_copy['comments'].astype(int)

In [42]:
df_copy.isnull().sum()

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

In [43]:
df_copy.duplicated().sum()

np.int64(2395)

In [44]:
df_copy=df_copy.drop_duplicates(keep='first')

In [45]:
df_copy.duplicated().sum()

np.int64(0)

In [46]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119696 entries, 0 to 122399
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              119696 non-null  object
 1   date                  119696 non-null  object
 2   views                 119696 non-null  int64
 3   likes                 119696 non-null  int64
 4   comments              119696 non-null  int64
 5   watch_time_minutes    119696 non-null  float64
 6   video_length_minutes  119696 non-null  float64
 7   subscribers           119696 non-null  int64
 8   category              119696 non-null  object
 9   device                119696 non-null  object
 10  country               119696 non-null  object
 11  ad_revenue_usd        119696 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 11.9+ MB

In [47]:
df_copy['video_id'] = pd.to_numeric(df_copy['video_id'].str.replace('vid_', ''),errors='coerce')

In [48]:
df_copy['date']=pd.to_datetime(df_copy['date']).dt.floor('s')

In [49]:
df_copy['category'].unique()

array(['Entertainment', 'Gaming', 'Education', 'Music', 'Tech',
       'Lifestyle'], dtype=object)

In [50]:
df_copy['device'].unique()

array(['TV', 'Tablet', 'Mobile', 'Desktop'], dtype=object)

In [51]:
from sklearn.preprocessing import LabelEncoder
encoder =LabelEncoder()
df_copy['category']=pd.to_numeric(encoder.fit_transform(df_copy['category']),errors='coerce')
df_copy['device']=pd.to_numeric(encoder.fit_transform(df_copy['device']),errors='coerce')

In [52]:
df_copy['country'].unique()

array(['IN', 'CA', 'UK', 'US', 'DE', 'AU'], dtype=object)

In [56]:
df_copy=df_copy.drop(columns=['country'], axis=1)

In [54]:
df_copy['engagement_rate'] = (df_copy['likes'] + df_copy['comments']) / df_copy['views']

In [57]:
df_copy

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,ad_revenue_usd,engagement_rate
0,3092,2024-09-24 10:50:40,9936,1221,320,26497.214184,2.862137,228086,1,2,203.178237,0.155093
1,3459,2024-09-22 10:50:40,10017,642,346,15209.747445,23.738069,736015,2,3,140.880508,0.098632
2,4784,2024-11-21 10:50:40,10097,1979,187,57332.658498,26.200634,240534,0,2,360.134008,0.214519
3,4078,2025-01-28 10:50:40,10034,1191,242,31334.517771,11.770340,434482,1,1,224.638261,0.142814
4,3522,2025-04-28 10:50:40,9889,1858,477,15665.666434,6.635854,42030,0,1,165.514388,0.236121
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,2902,2024-12-14 10:50:40,9853,1673,147,42075.704885,25.490195,210818,0,3,280.986396,0.184715
122396,3890,2024-07-13 10:50:40,10128,1709,63,57563.703040,16.229133,878860,4,0,354.612981,0.174961
122397,3934,2024-06-10 10:50:40,10267,700,0,27549.714659,23.822365,576756,5,3,203.643106,0.068180
122398,4260,2024-12-22 10:50:40,10240,1616,106,56967.384382,7.753099,585138,4,1,351.525811,0.168164
122399,1056,2024-06-25 10:50:40,9931,770,0,38466.837135,27.305703,517587,5,2,253.842824,0.077535

In [67]:
import pandas as pd

df = pd.read_csv(r"..\Data\youtube_ad_revenue_dataset.csv")
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [ ]:
from sklearn.preprocessing import LabelEncoder
df_copy = df.copy()

# Handle missing values
df_copy=df_copy.dropna(subset=['likes','comments','watch_time_minutes'], how='all') 
df_copy=df_copy.dropna(subset=['likes','comments'], how='all') 
df_copy=df_copy.fillna({'watch_time_minutes':df_copy['watch_time_minutes'].median()})
df_copy['likes'] = df_copy['likes'].fillna(0)
df_copy['likes'] = df_copy['likes'].astype(int)
df_copy['comments'] = df_copy['comments'].fillna(0)
df_copy['comments'] = df_copy['comments'].astype(int)

# delete the duplicate rows and keep the first occurrence
df_copy=df_copy.drop_duplicates(keep='first')

# Label encoding
encoder =LabelEncoder()
df_copy['category']=pd.to_numeric(encoder.fit_transform(df_copy['category']),errors='coerce')

df_copy=df_copy.drop(columns=['video_id'], axis=1) 
df_copy=df_copy.drop(columns=['date'], axis=1) 
df_copy=df_copy.drop(columns=['country'], axis=1) 
df_copy=df_copy.drop(columns=['device'], axis=1)
    
# Feature engineering
df_copy['engagement_rate'] = (df_copy['likes'] + df_copy['comments']) / df_copy['views']

df_copy.to_csv(r"../Data/Preprocessed_youtube_ad_revenue_dataset.csv", index=False)

In [82]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119696 entries, 0 to 122399
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   views                 119696 non-null  int64
 1   likes                 119696 non-null  int64
 2   comments              119696 non-null  int64
 3   watch_time_minutes    119696 non-null  float64
 4   video_length_minutes  119696 non-null  float64
 5   subscribers           119696 non-null  int64
 6   category              119696 non-null  int64
 7   ad_revenue_usd        119696 non-null  float64
 8   engagement_rate       119696 non-null  float64
dtypes: float64(4), int64(5)
memory usage: 9.1 MB

In [83]:
df_copy.isnull().sum()

views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
ad_revenue_usd          0
engagement_rate         0
dtype: int64

In [84]:
df_copy.duplicated().sum()

np.int64(0)

In [5]:
df_copy

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,ad_revenue_usd,category_encoded,engagement_rate
0,9936,1221,320,26497.214184,2.862137,228086,Entertainment,203.178237,1,0.155093
1,10017,642,346,15209.747445,23.738069,736015,Gaming,140.880508,2,0.098632
2,10097,1979,187,57332.658498,26.200634,240534,Education,360.134008,0,0.214519
3,10034,1191,242,31334.517771,11.770340,434482,Entertainment,224.638261,1,0.142814
4,9889,1858,477,15665.666434,6.635854,42030,Education,165.514388,0,0.236121
...,...,...,...,...,...,...,...,...,...,...
122395,9853,1673,147,42075.704885,25.490195,210818,Education,280.986396,0,0.184715
122396,10128,1709,63,57563.703040,16.229133,878860,Music,354.612981,4,0.174961
122397,10267,700,0,27549.714659,23.822365,576756,Tech,203.643106,5,0.068180
122398,10240,1616,106,56967.384382,7.753099,585138,Music,351.525811,4,0.168164
122399,9931,770,0,38466.837135,27.305703,517587,Tech,253.842824,5,0.077535

In [9]:
df_copy[['category','category_encoded']]

             category  category_encoded
0       Entertainment                 1
1              Gaming                 2
2           Education                 0
3       Entertainment                 1
4           Education                 0
...               ...               ...
122395      Education                 0
122396          Music                 4
122397           Tech                 5
122398          Music                 4
122399           Tech                 5

[119696 rows x 2 columns]