# Git Clone

In [ ]:
# clone git repository to local
!git clone https://github.com/PhonePe/pulse.git C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\MiniProject\PhonePeTransInsights\Data

In [ ]:
# clone git repository to local
import git

git_url = "https://github.com/PhonePe/pulse.git"
dest_path = r"C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\MiniProject\PhonePeTransInsights\Data"
git.Repo.clone_from(git_url,dest_path)
print("Repository cloned successfully")

Repository cloned successfully

In [2]:
# Declare a common function to read the json filenames

import glob

base_path = r"C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\MiniProject\PhonePeTransInsights\Data\data\**"

def get_json_file_list(required_path):
    base_folder_path = glob.glob(base_path+required_path,recursive=True)
    json_file_list=[]
    for state_folder_name in base_folder_path:
        json_folder_names = glob.glob(state_folder_name+"\\**\\*.json",recursive=True)
        for json_file_names in json_folder_names:
            json_file_list.append(json_file_names)
    return json_file_list

#json_file_list = get_json_file_list(r"\\aggregated\\insurance\\country\\india\\state\\")
#json_file_list

In [3]:
# Function to get data (state name, year, quarter) from json file path

def get_json_data(json_file):
    state_file_path = json_file.split('\\state\\')
    agg_values = state_file_path[1].split('\\')
    state_name = agg_values[0]
    year = agg_values[1]
    json_file_name = agg_values[2]
    return state_name,year,json_file_name

#json_file = "C:\\Users\\nisha\\OneDrive\\Desktop\\Nisha\\GUVI\\MiniProject\\PhonePeTransInsights\\Data\\data\\aggregated\\insurance\\country\\india\\state\\andaman-&-nicobar-islands\\2020\\2.json"
#get_json_data(json_file)

In [7]:
import json
import pandas as pd

# function to load the data from 'aggregated/transaction' folder present in pulse dataset
def get_aggregated_trans_load():
    json_file_list = get_json_file_list(r"\\aggregated\\transaction\\country\\india\\state\\")
    aggr_trans_value_dict = {'State':[],'Year':[],'Quarter':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        for values in json_data['data']['transactionData']:
            name = values['name']
            trans_count = values['paymentInstruments'][0]['count']
            trans_amount = values['paymentInstruments'][0]['amount']
            aggr_trans_value_dict['Transaction_type'].append(name)
            aggr_trans_value_dict['Transaction_count'].append(trans_count)
            aggr_trans_value_dict['Transaction_amount'].append(trans_amount)
            aggr_trans_value_dict['State'].append(agg_details[0])
            aggr_trans_value_dict['Year'].append(agg_details[1])
            aggr_trans_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(aggr_trans_value_dict)
    return df

In [8]:
aggr_trans_df = get_aggregated_trans_load()
aggr_trans_df

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [ ]:
import json
import pandas as pd

# function to load the data from 'aggregated/user' folder present in pulse dataset
def get_aggregated_user_load():
    json_file_list = get_json_file_list(r"\\aggregated\\user\\country\\india\\state\\")
    aggr_user_value_dict = { 'State':[],'Year':[],'Quarter':[],'User_Device_brand':[], 'User_Device_count':[], 'User_Device_percentange':[]}

    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        
        try:
            for values in json_data['data']['usersByDevice']:
                    brand = values['brand']
                    count = values['count']
                    perc = values['percentage']
                    aggr_user_value_dict['User_Device_brand'].append(brand)
                    aggr_user_value_dict['User_Device_count'].append(count)
                    aggr_user_value_dict['User_Device_percentange'].append(perc)
                    aggr_user_value_dict['State'].append(agg_details[0])
                    aggr_user_value_dict['Year'].append(agg_details[1])
                    aggr_user_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
        except:
             pass
    df=pd.DataFrame(aggr_user_value_dict)
    return df

In [12]:
aggr_user_df = get_aggregated_user_load()
aggr_user_df

,State,Year,Quarter,User_Device_brand,User_Device_count,User_Device_percentange
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [47]:
import json
import pandas as pd

# function to load the data from 'aggregated/insurance' folder present in pulse dataset
def get_aggregated_ins_load():
    json_file_list = get_json_file_list(r"\\aggregated\\insurance\\country\\india\\state\\")
    aggr_ins_value_dict = { 'State':[],'Year':[],'Quarter':[],'Payment_type':[],'Insurance_count':[], 'Insurance_amount':[]}

    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        for values in json_data['data']['transactionData']:
            name = values['name']
            ins_count = values['paymentInstruments'][0]['count']
            ins_amount = values['paymentInstruments'][0]['amount']
            aggr_ins_value_dict['Payment_type'].append(name)
            aggr_ins_value_dict['Insurance_count'].append(ins_count)
            aggr_ins_value_dict['Insurance_amount'].append(ins_amount)
            aggr_ins_value_dict['State'].append(agg_details[0])
            aggr_ins_value_dict['Year'].append(agg_details[1])
            aggr_ins_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(aggr_ins_value_dict)
    return df

In [48]:
aggr_ins_df = get_aggregated_ins_load()
aggr_ins_df

,State,Year,Quarter,Payment_type,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [53]:
import json
import pandas as pd

# function to load the data from 'map/transaction' folder present in pulse dataset
def get_map_trans_load():
    json_file_list = get_json_file_list(r"\\map\\transaction\\hover\\country\\india\\state\\")
    map_trans_value_dict = { 'State':[],'Year':[],'Quarter':[],'District':[], 'Transaction_count':[], 'Transaction_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        for values in json_data['data']['hoverDataList']:
            name = values['name'].split(' district')[0]
            trans_count = values['metric'][0]['count']
            trans_amount = values['metric'][0]['amount']
            map_trans_value_dict['District'].append(name)
            map_trans_value_dict['Transaction_count'].append(trans_count)
            map_trans_value_dict['Transaction_amount'].append(trans_amount)
            map_trans_value_dict['State'].append(agg_details[0])
            map_trans_value_dict['Year'].append(agg_details[1])
            map_trans_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(map_trans_value_dict)
    return df

In [54]:
map_trans_df = get_map_trans_load()
map_trans_df

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur,67833775,1.142771e+11

In [55]:
import json
import pandas as pd

# function to load the data from 'map/user' folder present in pulse dataset 20608
def get_map_user_load():
    json_file_list = get_json_file_list(r"\\map\\user\\hover\\country\\india\\state\\")
    map_user_value_dict = { 'State':[],'Year':[],'Quarter':[],'District':[], 'Total_Registered_users':[], 'Total_App_Opens':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        for key,values in json_data['data']['hoverData'].items():
            district = key.split(' district')[0]
            registered_user_count =values['registeredUsers']
            app_opens_count =values['appOpens']
            map_user_value_dict['District'].append(district)
            map_user_value_dict['Total_Registered_users'].append(registered_user_count)
            map_user_value_dict['Total_App_Opens'].append(app_opens_count)
            map_user_value_dict['State'].append(agg_details[0])
            map_user_value_dict['Year'].append(agg_details[1])
            map_user_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(map_user_value_dict)
    return df

In [56]:
map_user_df = get_map_user_load()
map_user_df

,State,Year,Quarter,District,Total_Registered_users,Total_App_Opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman,1468252,80543469
20605,west-bengal,2024,4,nadia,1861738,98740305
20606,west-bengal,2024,4,birbhum,1114220,73465525
20607,west-bengal,2024,4,purba medinipur,1717074,108350777

In [57]:
import json
import pandas as pd

# function to load the data from 'map/insurance' folder present in pulse dataset
def get_map_ins_load():
    json_file_list = get_json_file_list(r"\\map\\insurance\\hover\\country\\india\\state\\")
    map_ins_value_dict = { 'State':[],'Year':[],'Quarter':[],'District':[], 'Insurance_count':[], 'Insurance_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
        for values in json_data['data']['hoverDataList']:
            name = values['name']
            ins_count = values['metric'][0]['count']
            ins_amount = values['metric'][0]['amount']
            map_ins_value_dict['District'].append(name)
            map_ins_value_dict['Insurance_count'].append(ins_count)
            map_ins_value_dict['Insurance_amount'].append(ins_amount)
            map_ins_value_dict['State'].append(agg_details[0])
            map_ins_value_dict['Year'].append(agg_details[1])
            map_ins_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(map_ins_value_dict)
    return df

In [58]:
map_ins_df = get_map_ins_load()
map_ins_df

,State,Year,Quarter,District,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

In [4]:
import json
import pandas as pd

# function to load the data from 'top/transaction' folder present in pulse dataset. District values will be loaded.
def get_top_trans_dist_load():
    json_file_list = get_json_file_list(r"\\top\\transaction\\country\\india\\state\\")
    top_trans_dist_value_dict = {'State':[], 'Year':[],'Quarter':[],
                                    'District':[],'District_Transaction_count':[],'District_Transaction_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['districts']:
            district_name =values['entityName']
            dist_trans_count = values['metric']['count']
            dist_trans_amount = values['metric']['amount']
            top_trans_dist_value_dict['District'].append(district_name)
            top_trans_dist_value_dict['District_Transaction_count'].append(dist_trans_count)
            top_trans_dist_value_dict['District_Transaction_amount'].append(dist_trans_amount)
            top_trans_dist_value_dict['State'].append(agg_details[0])
            top_trans_dist_value_dict['Year'].append(agg_details[1])
            top_trans_dist_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_trans_dist_value_dict)
    return df
        
get_top_trans_dist_load()

,State,Year,Quarter,District,District_Transaction_count,District_Transaction_amount
0,andaman-&-nicobar-islands,2018,1,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,2,south andaman,9395,2.394824e+07
4,andaman-&-nicobar-islands,2018,2,nicobars,1120,3.072437e+06
...,...,...,...,...,...,...
8291,west-bengal,2024,4,howrah,67496284,1.025764e+11
8292,west-bengal,2024,4,nadia,65274337,1.079320e+11
8293,west-bengal,2024,4,malda,63424613,1.024212e+11
8294,west-bengal,2024,4,hooghly,59676576,9.071383e+10
8295,west-bengal,2024,4,paschim medinipur,58238212,8.431774e+10

In [60]:
import json
import pandas as pd

# function to load the data from 'top/transaction' folder present in pulse dataset. Pincode values will be loaded.
def get_top_trans_pincode_load():
    json_file_list = get_json_file_list(r"\\top\\transaction\\country\\india\\state\\")
    top_trans_pin_value_dict = {'State':[], 'Year':[],'Quarter':[],
                                'PinCode':[],'PinCode_Transaction_count':[],'PinCode_Transaction_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['pincodes']:
            pincode_name =values['entityName']
            pin_trans_count = values['metric']['count']
            pin_trans_amount = values['metric']['amount']
            top_trans_pin_value_dict['PinCode'].append(pincode_name)
            top_trans_pin_value_dict['PinCode_Transaction_count'].append(pin_trans_count)
            top_trans_pin_value_dict['PinCode_Transaction_amount'].append(pin_trans_amount)
            top_trans_pin_value_dict['State'].append(agg_details[0])
            top_trans_pin_value_dict['Year'].append(agg_details[1])
            top_trans_pin_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_trans_pin_value_dict)
    return df
        
get_top_trans_pincode_load()

,State,Year,Quarter,PinCode,PinCode_Transaction_count,PinCode_Transaction_amount
0,andaman-&-nicobar-islands,2018,1,744101,1622,2.769298e+06
1,andaman-&-nicobar-islands,2018,1,744103,1223,2.238042e+06
2,andaman-&-nicobar-islands,2018,1,744102,969,3.519060e+06
3,andaman-&-nicobar-islands,2018,1,744105,685,1.298561e+06
4,andaman-&-nicobar-islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,west-bengal,2024,4,711101,6753348,1.049483e+10
9995,west-bengal,2024,4,700059,6662715,8.009476e+09
9996,west-bengal,2024,4,700039,6575693,9.018748e+09
9997,west-bengal,2024,4,734001,6432082,8.996529e+09
9998,west-bengal,2024,4,733134,6313560,1.050259e+10

In [62]:
import json
import pandas as pd

# function to load the data from 'top/user' folder present in pulse dataset. District values will be loaded.
def get_top_user_dist_load():
    json_file_list = get_json_file_list(r"\\top\\user\\country\\india\\state\\")
    top_user_dist_value_dict = {'State':[], 'Year':[],'Quarter':[],'District':[],'Registered_users':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['districts']:
            district_name =values['name']
            reg_user = values['registeredUsers']
            top_user_dist_value_dict['District'].append(district_name)
            top_user_dist_value_dict['Registered_users'].append(reg_user)
            top_user_dist_value_dict['State'].append(agg_details[0])
            top_user_dist_value_dict['Year'].append(agg_details[1])
            top_user_dist_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_user_dist_value_dict)
    return df
        
get_top_user_dist_load()

,State,Year,Quarter,District,Registered_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,west-bengal,2024,4,hooghly,1957356
8292,west-bengal,2024,4,nadia,1861738
8293,west-bengal,2024,4,purba medinipur,1717074
8294,west-bengal,2024,4,paschim medinipur,1522845
8295,west-bengal,2024,4,paschim bardhaman,1468252

In [63]:
import json
import pandas as pd

# function to load the data from 'top/user' folder present in pulse dataset. Pincodes values will be loaded.
def get_top_user_pincode_load():
    json_file_list = get_json_file_list(r"\\top\\user\\country\\india\\state\\")
    top_user_pin_value_dict = {'State':[], 'Year':[],'Quarter':[],'Pincodes':[],'Registered_users':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['pincodes']:
            pincodes =values['name']
            reg_user = values['registeredUsers']
            top_user_pin_value_dict['Pincodes'].append(pincodes)
            top_user_pin_value_dict['Registered_users'].append(reg_user)
            top_user_pin_value_dict['State'].append(agg_details[0])
            top_user_pin_value_dict['Year'].append(agg_details[1])
            top_user_pin_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_user_pin_value_dict)
    return df
        
get_top_user_pincode_load()

                          State  Year  Quarter Pincodes  Registered_users
0     andaman-&-nicobar-islands  2018        1   744103              1608
1     andaman-&-nicobar-islands  2018        1   744101              1108
2     andaman-&-nicobar-islands  2018        1   744105              1075
3     andaman-&-nicobar-islands  2018        1   744102              1006
4     andaman-&-nicobar-islands  2018        1   744104               272
...                         ...   ...      ...      ...               ...
9995                west-bengal  2024        4   733134            169596
9996                west-bengal  2024        4   700059            169448
9997                west-bengal  2024        4   711302            146034
9998                west-bengal  2024        4   700150            142151
9999                west-bengal  2024        4   711106            142077

[10000 rows x 5 columns]

In [64]:
import json
import pandas as pd

# function to load the data from 'top/insurance' folder present in pulse dataset. District values will be loaded.
def get_top_ins_dist_load():
    json_file_list = get_json_file_list(r"\\top\\insurance\\country\\india\\state\\")
    top_ins_dist_value_dict = {'State':[], 'Year':[],'Quarter':[],
                            'District':[],'District_Insurance_count':[],'District_Insurance_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['districts']:
            district_name =values['entityName']
            dist_ins_count = values['metric']['count']
            dist_ins_amount = values['metric']['amount']
            top_ins_dist_value_dict['District'].append(district_name)
            top_ins_dist_value_dict['District_Insurance_count'].append(dist_ins_count)
            top_ins_dist_value_dict['District_Insurance_amount'].append(dist_ins_amount)
            top_ins_dist_value_dict['State'].append(agg_details[0])
            top_ins_dist_value_dict['Year'].append(agg_details[1])
            top_ins_dist_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_ins_dist_value_dict)
    return df
        
get_top_ins_dist_load()

,State,Year,Quarter,District,District_Insurance_count,District_Insurance_amount
0,andaman-&-nicobar-islands,2020,2,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,3,south andaman,35,13651.0
3,andaman-&-nicobar-islands,2020,3,nicobars,5,1448.0
4,andaman-&-nicobar-islands,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,west-bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,west-bengal,2024,4,paschim medinipur,4155,5405054.0
5605,west-bengal,2024,4,malda,4042,4902098.0
5606,west-bengal,2024,4,nadia,3807,5031294.0
5607,west-bengal,2024,4,purba bardhaman,3595,4482879.0

In [65]:
import json
import pandas as pd

# function to load the data from 'top/insurance' folder present in pulse dataset. Pincodes values will be loaded.
def get_top_ins_pincode_load():
    json_file_list = get_json_file_list(r"\\top\\insurance\\country\\india\\state\\")
    top_ins_pin_value_dict = {'State':[], 'Year':[],'Quarter':[],
                            'Pincode':[],'Pincode_Insurance_count':[],'Pincode_Insurance_amount':[]}
    for json_file in json_file_list:
        agg_details = get_json_data(json_file)
        data = open(json_file,'r')
        json_data = json.load(data)
           
        for values in json_data['data']['pincodes']:
            pincode =values['entityName']
            pin_ins_count = values['metric']['count']
            pin_ins_amount = values['metric']['amount']
            top_ins_pin_value_dict['Pincode'].append(pincode)
            top_ins_pin_value_dict['Pincode_Insurance_count'].append(pin_ins_count)
            top_ins_pin_value_dict['Pincode_Insurance_amount'].append(pin_ins_amount)
            top_ins_pin_value_dict['State'].append(agg_details[0])
            top_ins_pin_value_dict['Year'].append(agg_details[1])
            top_ins_pin_value_dict['Quarter'].append(int(agg_details[2].strip('.json')))
    
    df=pd.DataFrame(top_ins_pin_value_dict)
    return df
        
get_top_ins_pincode_load()

,State,Year,Quarter,Pincode,Pincode_Insurance_count,Pincode_Insurance_amount
0,andaman-&-nicobar-islands,2020,2,744301,3,565.0
1,andaman-&-nicobar-islands,2020,2,744104,2,513.0
2,andaman-&-nicobar-islands,2020,2,744101,1,282.0
3,andaman-&-nicobar-islands,2020,3,744112,9,3432.0
4,andaman-&-nicobar-islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,west-bengal,2024,4,711101,713,750354.0
6664,west-bengal,2024,4,700091,642,969634.0
6665,west-bengal,2024,4,700150,627,761501.0
6666,west-bengal,2024,4,700039,619,787836.0
6667,west-bengal,2024,4,700156,574,888613.0