# 22 April 2026

In [15]:
import pandas as pd

df = pd.read_csv(r'C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\MiniProject\AmazonMusicClustering\Data\single_genre_artists.csv')
df.head()

,id_songs,name_song,popularity_songs,duration_ms,explicit,id_artists,release_date,danceability,energy,key,...,acousticness,instrumentalness,liveness,valence,tempo,time_signature,followers,genres,name_artists,popularity_artists
0,0IA0Hju8CAgYfV1hwhidBH,La Java,0,161427,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.563,0.184,4,...,0.993,0.000016,0.325,0.654,133.088,3,5078.0,['vintage chanson'],Mistinguett,22
1,1b8HZQCqcqwbzlA1jRTp6E,En Douce,0,223440,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.427,0.180,10,...,0.989,0.000000,0.128,0.431,78.459,3,5078.0,['vintage chanson'],Mistinguett,22
2,5d5gQxHwYovxR5pqETOIAa,J'en Ai Marre,0,208267,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.511,0.206,0,...,0.995,0.000000,0.418,0.481,70.443,4,5078.0,['vintage chanson'],Mistinguett,22
3,1EO65UEEPfy7CR0NK2sDxy,Ils n'ont pas ca,0,161933,0,4AxgXfD7ISvJSTObqm4aIE,1924,0.676,0.467,9,...,0.991,0.000000,0.219,0.726,129.775,4,5078.0,['vintage chanson'],Mistinguett,22
4,6a58gXSgqbIsXUhVZ6ZJqe,La belote,0,167973,0,4AxgXfD7ISvJSTObqm4aIE,1924,0.650,0.298,9,...,0.991,0.000000,0.373,0.844,75.950,4,5078.0,['vintage chanson'],Mistinguett,22

# 24 April 2026

In [16]:
df.shape

(95837, 23)

In [17]:
df_copy = df.copy()

In [18]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95837 entries, 0 to 95836
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_songs            95837 non-null  object
 1   name_song           95837 non-null  object
 2   popularity_songs    95837 non-null  int64
 3   duration_ms         95837 non-null  int64
 4   explicit            95837 non-null  int64
 5   id_artists          95837 non-null  object
 6   release_date        95837 non-null  object
 7   danceability        95837 non-null  float64
 8   energy              95837 non-null  float64
 9   key                 95837 non-null  int64
 10  loudness            95837 non-null  float64
 11  mode                95837 non-null  int64
 12  speechiness         95837 non-null  float64
 13  acousticness        95837 non-null  float64
 14  instrumentalness    95837 non-null  float64
 15  liveness            95837 non-null  float64
 16  valence             95837 non-null  float64
 17  tempo               95837 non-null  float64
 18  time_signature      95837 non-null  int64
 19  followers           95837 non-null  float64
 20  genres              95837 non-null  object
 21  name_artists        95837 non-null  object
 22  popularity_artists  95837 non-null  int64
dtypes: float64(10), int64(7), object(6)
memory usage: 16.8+ MB

In [19]:
df_copy.isnull().sum()

id_songs              0
name_song             0
popularity_songs      0
duration_ms           0
explicit              0
id_artists            0
release_date          0
danceability          0
energy                0
key                   0
loudness              0
mode                  0
speechiness           0
acousticness          0
instrumentalness      0
liveness              0
valence               0
tempo                 0
time_signature        0
followers             0
genres                0
name_artists          0
popularity_artists    0
dtype: int64

In [20]:
df_copy.duplicated().sum()

np.int64(0)

In [21]:
df_copy.columns

Index(['id_songs', 'name_song', 'popularity_songs', 'duration_ms', 'explicit',
       'id_artists', 'release_date', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature', 'followers', 'genres',
       'name_artists', 'popularity_artists'],
      dtype='object')

In [22]:
df_copy.head()

,id_songs,name_song,popularity_songs,duration_ms,explicit,id_artists,release_date,danceability,energy,key,...,acousticness,instrumentalness,liveness,valence,tempo,time_signature,followers,genres,name_artists,popularity_artists
0,0IA0Hju8CAgYfV1hwhidBH,La Java,0,161427,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.563,0.184,4,...,0.993,0.000016,0.325,0.654,133.088,3,5078.0,['vintage chanson'],Mistinguett,22
1,1b8HZQCqcqwbzlA1jRTp6E,En Douce,0,223440,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.427,0.180,10,...,0.989,0.000000,0.128,0.431,78.459,3,5078.0,['vintage chanson'],Mistinguett,22
2,5d5gQxHwYovxR5pqETOIAa,J'en Ai Marre,0,208267,0,4AxgXfD7ISvJSTObqm4aIE,1922,0.511,0.206,0,...,0.995,0.000000,0.418,0.481,70.443,4,5078.0,['vintage chanson'],Mistinguett,22
3,1EO65UEEPfy7CR0NK2sDxy,Ils n'ont pas ca,0,161933,0,4AxgXfD7ISvJSTObqm4aIE,1924,0.676,0.467,9,...,0.991,0.000000,0.219,0.726,129.775,4,5078.0,['vintage chanson'],Mistinguett,22
4,6a58gXSgqbIsXUhVZ6ZJqe,La belote,0,167973,0,4AxgXfD7ISvJSTObqm4aIE,1924,0.650,0.298,9,...,0.991,0.000000,0.373,0.844,75.950,4,5078.0,['vintage chanson'],Mistinguett,22

In [9]:
df_copy.drop(['id_songs','popularity_songs','duration_ms','explicit','id_artists',
              'release_date','key','mode','time_signature','followers','name_artists','popularity_artists'], axis=1,inplace=True)

In [10]:
df_copy['genres'] = df_copy['genres'].str.strip("[]").str.replace("'", "")

In [11]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95837 entries, 0 to 95836
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name_song         95837 non-null  object
 1   danceability      95837 non-null  float64
 2   energy            95837 non-null  float64
 3   loudness          95837 non-null  float64
 4   speechiness       95837 non-null  float64
 5   acousticness      95837 non-null  float64
 6   instrumentalness  95837 non-null  float64
 7   liveness          95837 non-null  float64
 8   valence           95837 non-null  float64
 9   tempo             95837 non-null  float64
 10  genres            95837 non-null  object
dtypes: float64(9), object(2)
memory usage: 8.0+ MB

In [12]:
df_copy

,name_song,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genres
0,La Java,0.563,0.1840,-13.757,0.0512,0.993,0.000016,0.3250,0.654,133.088,vintage chanson
1,En Douce,0.427,0.1800,-15.375,0.0670,0.989,0.000000,0.1280,0.431,78.459,vintage chanson
2,J'en Ai Marre,0.511,0.2060,-15.514,0.0592,0.995,0.000000,0.4180,0.481,70.443,vintage chanson
3,Ils n'ont pas ca,0.676,0.4670,-12.393,0.1650,0.991,0.000000,0.2190,0.726,129.775,vintage chanson
4,La belote,0.650,0.2980,-13.806,0.1380,0.991,0.000000,0.3730,0.844,75.950,vintage chanson
...,...,...,...,...,...,...,...,...,...,...,...
95832,Freaks,0.674,0.5680,-6.356,0.0408,0.116,0.000000,0.1650,0.640,166.107,alt z
95833,下雨天,0.528,0.6730,-3.639,0.0314,0.143,0.000000,0.0989,0.297,130.066,chinese viral pop
95834,The Cutest Puppy,0.609,0.0172,-28.573,0.1180,0.996,0.973000,0.1080,0.890,68.619,instrumental lullaby
95835,John Brown's Song,0.562,0.0331,-25.551,0.1030,0.996,0.961000,0.1110,0.386,63.696,instrumental lullaby
95836,云与海,0.560,0.5180,-7.471,0.0292,0.785,0.000000,0.0648,0.211,131.896,chinese viral pop

In [13]:
df_copy['genres'].value_counts()

genres
hoerspiel                        8027
kleine hoerspiel                 2081
                                 1876
classic israeli pop              1180
vintage taiwan pop               1097
                                 ...
italian mezzo-soprano               1
deep discofox                       1
pinoy praise                        1
lithuanian metal                    1
chinese classical performance       1
Name: count, Length: 3153, dtype: int64

In [14]:
df_copy.to_csv(r'C:\Users\nisha\OneDrive\Desktop\Nisha\GUVI\MiniProject\AmazonMusicClustering\Data\single_genre_artists_cleaned.csv', index=False)

In [91]:
df_copy.columns

Index(['name_song', 'danceability', 'energy', 'loudness', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genres'],
      dtype='object')